apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
  namespace: $NAME_SPACE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - image: $IMAGE_NAME
        name: $APP_NAME
        env:
        - name: DATA_FILE
          value: $DATA_FILE
      imagePullSecrets:
      - name: regcred
