jobs:
  - job: dockerLogin
    displayName: 'Docker Login'
    steps:
    - bash: |
        #!/bin/bash
        cat ~/.docker/config.json
      displayName: 'Verify Login before'

    - task: Docker@2
      displayName: 'Login to Container Registry'
      inputs:
        containerRegistry: ${{ parameters.dockerServiceConnection }}
        command: 'login'

    - bash: |
        #!/bin/bash
        cat ~/.docker/config.json
      displayName: 'Verify Login after'